[package]
name = "probos"
version = "0.0.1"
authors = ["Aleksi Backman"]

[lib]
crate-type = ["staticlib"] # Library that contains all of its dependencies

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
